---
- name: Run yum update
  hosts: all
  become: yes
  gather_facts: no  # Skip because system Python might not be ready

  tasks:
    - name: Run yum update to update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
