---
- name: Install python3-dnf via raw module
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install python3-dnf
      ansible.builtin.raw: dnf install -y python3-dnf
      register: result
      changed_when: "'Complete!' in result.stdout"